### ISSUE TITLE
Properly read and encode special characters

### ISSUE THREAD

**Issue by camd67** [camd67/moebot-py-archive#4]
Currently, if you run `moebot top 5` the result includes Gintama` which displays in Discord as:
`Gintama&amp;#039;`

when it should be:
`Gintama``

**Comment by camd67** [comment]
This also occurs when asking for anime > 50. It encodes the value as text instead of a number.

**Comment by Nick-Anderssohn** [comment]
switched the part where its asking for anime to strconv.Itoa() which should fix that

**Comment by Nick-Anderssohn** [comment]
the `Gintama&amp;#039` isn't a casting issue, thats the literal text taken from the html.  Any ideas for a solution?  Manually scan/check for `&amp;#039` and replace with `? ...I would do this fix in the topanime package
